# Generated by Django 6.0.7 on 2026-07-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_cart_wishlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
